version: '3.8'

services:
  backend_for_frontend:
    image: backend_for_frontend
    build:
      context: .
      dockerfile: Services/BackendForFrontend/Dockerfile
  
  
  customer_api:
    image: customer_api
    build:
      context: .
      dockerfile: Services/Customer.API/Dockerfile
  
  
  notification_api:
    image: notification_api
    build:
      context: .
      dockerfile: Services/Notification.API/Dockerfile
  
  
  customer_db:
    image: postgres
  
  
  notification_db:
    image: redis


  rabbitmq:
    image: rabbitmq:3-management-alpine  
    
    
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.60.0
    
    
  jaeger:
    image: jaegertracing/all-in-one:latest
    
    
  prometheus:
    image: prom/prometheus:latest
    
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.1
    
  kibana:
    image: docker.elastic.co/kibana/kibana:7.14.1